"""empty message

Revision ID: dcba64361a42
Revises: 32dfb24b3300
Create Date: 2024-10-23 13:45:50.399242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcba64361a42'
down_revision = '32dfb24b3300'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_data', sa.DateTime(), nullable=False))
        batch_op.drop_column('create_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_date', sa.DATETIME(), nullable=False))
        batch_op.drop_column('create_data')

    # ### end Alembic commands ###
